### PR TITLE
Authentication and Dashboard

### PR DESCRIPTION
**Pull request by anand-yadav55**

### CODE REVIEW

**Comment by DesignrKnight** [comment]
@riteshsp2000 
Do give a look

**Comment by DesignrKnight** [comment]
Also, @anand-yadav55 
There are merge conflicts. Do resolve them

**Comment by anand-yadav55** [comment]
> Also, @anand-yadav55
> There are merge conflicts. Do resolve them

Conflicting files are: 
package-lock.json
yarn.lock

I have removed these files from commit this time because they are auto generated on install.

**Comment by DesignrKnight** [comment]
Yes, I understand you removed, but as there is conflict, you need to resolve it. It would be helpful if you resolve it. 
Fetch the master and merge it with your branch and update PR

**Comment by DesignrKnight** [comment]
Thanks so much @anand-yadav55 for fixing the issues

**Pull request merged**
